### ISSUE TITLE
Arrays not supported converting SQL -> DBML (postgres)

### ISSUE THREAD

**Issue by rolandpeelen** [holistics/dbml#174]
I'm not sure what is expected here. Are Arrays supported to begin with?

CLI version: 2.3.0

Reproduction example:
```sql
CREATE TABLE foo (
    bar text[]
);
```

Command:
```bash
sql2dbml --postgres foo.sql -o foo.dbml
```

Returns:
```bash
  ERROR: You have a syntax error at "foo.sql" line 2 column 13. Expected ")", ",", "CHECK", "CONSTRAINT", "DEFAULT", "GENERATED", "NOT", "NULL", "PRIMARY", "REFERENCES", "UNIQUE", or space but "[" found.

  A complete log can be found in:
    ...
```

Log after fresh run:
```javascript
2021-05-01T15:32:57.202Z
SyntaxError: You have a syntax error at "foo.sql" line 2 column 13. Expected ")", ",", "CHECK", "CONSTRAINT", "DEFAULT", "GENERATED", "NOT", "NULL", "PRIMARY", "REFERENCES", "UNIQUE", or space but "[" found.
    at /Users/--/.config/yarn/global/node_modules/@dbml/cli/lib/cli/utils.js:55:13
    at Array.forEach (<anonymous>)
    at generate (/Users/--/.config/yarn/global/node_modules/@dbml/cli/lib/cli/utils.js:48:14)
    at importHandler (/Users/--/.config/yarn/global/node_modules/@dbml/cli/lib/cli/import.js:40:27)
    at Object.sql2dbml (/Users/--/.config/yarn/global/node_modules/@dbml/cli/lib/cli/index.js:38:23)
    at Object.<anonymous> (/Users/--/.config/yarn/global/node_modules/@dbml/cli/bin/sql2dbml.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)

ROOT_ERROR:
SyntaxError: Expected ")", ",", "CHECK", "CONSTRAINT", "DEFAULT", "GENERATED", "NOT", "NULL", "PRIMARY", "REFERENCES", "UNIQUE", or space but "[" found.
    at peg$buildStructuredError (/Users/--/.config/yarn/global/node_modules/@dbml/core/lib/parse/postgresParser.js:33:6718)
    at Object.peg$parse [as parse] (/Users/--/.config/yarn/global/node_modules/@dbml/core/lib/parse/postgresParser.js:41:339)
    at Function.parsePostgresToJSON (/Users/--/.config/yarn/global/node_modules/@dbml/core/lib/parse/Parser.js:51:41)
    at Function.parse (/Users/--/.config/yarn/global/node_modules/@dbml/core/lib/parse/Parser.js:79:32)
    at Object._import [as import] (/Users/--/.config/yarn/global/node_modules/@dbml/core/lib/import/index.js:15:37)
    at /Users/--/.config/yarn/global/node_modules/@dbml/cli/lib/cli/import.js:40:68
    at /Users/--/.config/yarn/global/node_modules/@dbml/cli/lib/cli/utils.js:52:23
    at Array.forEach (<anonymous>)
    at generate (/Users/--/.config/yarn/global/node_modules/@dbml/cli/lib/cli/utils.js:48:14)
    at importHandler (/Users/--/.config/yarn/global/node_modules/@dbml/cli/lib/cli/import.js:40:27)
{"start":{"offset":31,"line":2,"column":13},"end":{"offset":32,"line":2,"column":14}}
```

**Comment by mkaatman** [comment]
Potentially similar to https://github.com/holistics/dbml/issues/126

**Comment by rolandpeelen** [comment]
@mkaatman - If you can point me to where this is implemented, I'd be happy to take a look and see if I can fix the error / make a PR 🤞

**Comment by Benoss** [comment]
I have the same issue, was a bit painful to import the model. Maybe an option to ignore a column if there is a problem on it would could help in the mean time.

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/192

**Comment by rolandpeelen** [comment]
Thanks! Will have a go at this somewhere next week 🚀
