### ISSUE TITLE
dbml2sql Syntax Error on first character of .sql file

### ISSUE THREAD

**Issue by jakedeg** [holistics/dbml#191]
Hello! I'm trying to use `dbml/cli` and hitting a syntax error. I saw that @Marco4C opened a similar issue [here](https://github.com/holistics/dbml/issues/181), but I can't tell why they closed it.

In my case, `dbml/cli` is unable to process any of my .sql dumps and keeps complaining about a syntax error on the first character no matter what it is. By default, my .sql file (pg_dumped from Postgres 13) looks like this:
```--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;
...
```
...and then a bunch more.

When I run `dbml2sql`, I get: 
```ROOT_ERROR:
SyntaxError: Expected Table Group, comment, end of input, enum, project, references, table, or whitespace but "-" found.
    at peg$buildStructuredError (/usr/local/lib/node_modules/@dbml/cli/node_modules/@dbml/core/lib/parse/dbmlParser.js:1086:12)
    at Object.peg$parse [as parse] (/usr/local/lib/node_modules/@dbml/cli/node_modules/@dbml/core/lib/parse/dbmlParser.js:7609:11)
    at Function.parseDBMLToJSON (/usr/local/lib/node_modules/@dbml/cli/node_modules/@dbml/core/lib/parse/Parser.js:56:37)
    at Function.parse (/usr/local/lib/node_modules/@dbml/cli/node_modules/@dbml/core/lib/parse/Parser.js:83:32)
    at Object._export [as export] (/usr/local/lib/node_modules/@dbml/cli/node_modules/@dbml/core/lib/export/index.js:15:37)
    at /usr/local/lib/node_modules/@dbml/cli/lib/cli/export.js:38:69
    at /usr/local/lib/node_modules/@dbml/cli/lib/cli/utils.js:52:23
    at Array.forEach (<anonymous>)
    at generate (/usr/local/lib/node_modules/@dbml/cli/lib/cli/utils.js:48:14)
    at exportHandler (/usr/local/lib/node_modules/@dbml/cli/lib/cli/export.js:38:27)
{"start":{"offset":0,"line":1,"column":1},"end":{"offset":1,"line":1,"column":2}}```

Of course, that "-" it's complaining about _is_ a comment, right? Which it says it would expect?

I've tried deleting the comments from the head of the file and letting it start with `SET statement_timeout = 0;` but then I just get `SyntaxError: Expected Table Group, comment, end of input, enum, project, references, table, or whitespace but "S" found.`

**Comment by NQPhuc** [comment]
Hi, `dbml2sql` tool is for converting dbml files into sql. For the other way around, try using `sql2dbml`. (https://www.dbml.org/cli/#convert-a-sql-file-to-dbml)
