### ISSUE TITLE
SQL Server Connector Generates Duplicate Refs and Enums

### ISSUE THREAD

**Issue by asadcr** [holistics/dbml#669]
so i ran `db2dbml mssql "Connection String"` and 

it has been failing with these errors

```
 ERROR: Error: Enum "dbo"."CC_Address_Info_AddressID_AddressFormatID" existed
```

Here's the full stack trace

```
Error: Error: Enum "dbo"."CC_Address_Info_AddressID_AddressFormatID" existed
    at generateDatabase (/Users/asadali/Downloads/dbml-master/packages/dbml-core/lib/parse/databaseGenerator.js:115:11)
    at Object.generateDbml (/Users/asadali/Downloads/dbml-master/packages/dbml-core/lib/import/index.js:17:58)
    at connectionHandler (/Users/asadali/Downloads/dbml-master/packages/dbml-cli/src/cli/connector.ts:17:26)
    at Object.<anonymous> (/Users/asadali/Downloads/dbml-master/packages/dbml-cli/src/cli/connector.ts:28:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.m._compile (/Users/asadali/.nvm/versions/node/v20.11.0/lib/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/asadali/.nvm/versions/node/v20.11.0/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
```

So i debugged the whole code and turns out [fetchSchemaJson](https://github.com/holistics/dbml/blob/d63ebd60bc967a794cd093ecb712b3a15a149783/packages/dbml-connector/src/connectors/mssqlConnector.ts#L579) generates duplicate entries here

so in `enums` section it generated this 

```
{
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    },
    {
      "name": "CC_Address_Info_AddressID_AddressFormatID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000001"
        },
        {
          "name": "176029FA-D6D3-49E1-A48C-000000000002"
        }
      ]
    }
```

One entry was duplicated so many times.

Next Error

```
Error: Error: Enum value "6CC75003-9199-11D4-AF4C-000102C2C966" existed in enum "dbo"."CC_Contact_Lst_SclYearInfoID"
    at generateDatabase (/Users/asadali/Downloads/dbml-master/packages/dbml-core/lib/parse/databaseGenerator.js:115:11)
    at Object.generateDbml (/Users/asadali/Downloads/dbml-master/packages/dbml-core/lib/import/index.js:17:58)
    at connectionHandler (/Users/asadali/Downloads/dbml-master/packages/dbml-cli/src/cli/connector.ts:17:26)
    at Object.<anonymous> (/Users/asadali/Downloads/dbml-master/packages/dbml-cli/src/cli/connector.ts:28:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.m._compile (/Users/asadali/.nvm/versions/node/v20.11.0/lib/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/asadali/.nvm/versions/node/v20.11.0/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
```

Same Case

```
{
      "name": "CC_Contact_Lst_SclYearInfoID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "6CC75003-9199-11D4-AF4C-000102C2C966"
        },
        {
          "name": "4EEAFF43-5A29-4366-93D5-E866EA8A6FB5"
        },
        {
          "name": "6CC75003-9199-11D4-AF4C-000102C2C966"
        },
        {
          "name": "4EEAFF43-5A29-4366-93D5-E866EA8A6FB5"
        }
      ]
    },
    {
      "name": "CC_Contact_Lst_SclYearInfoID",
      "schemaName": "dbo",
      "values": [
        {
          "name": "6CC75003-9199-11D4-AF4C-000102C2C966"
        },
        {
          "name": "4EEAFF43-5A29-4366-93D5-E866EA8A6FB5"
        },
        {
          "name": "6CC75003-9199-11D4-AF4C-000102C2C966"
        },
        {
          "name": "4EEAFF43-5A29-4366-93D5-E866EA8A6FB5"
        }
      ]
    },
```
Had to remove the duplicate entries to fix the Data.

Next Error has the same case

```
Error: Error: Reference with the same endpoints already exists: "dbo"."WebPortal_Security_User_Type_Lst"("User_Type_ID") references "dbo"."WebPortal_Security_User_Types"("User_Type_ID")
    at generateDatabase (/Users/asadali/Downloads/dbml-master/packages/dbml-core/lib/parse/databaseGenerator.js:115:11)
    at Object.generateDbml (/Users/asadali/Downloads/dbml-master/packages/dbml-core/lib/import/index.js:17:58)
    at connectionHandler (/Users/asadali/Downloads/dbml-master/packages/dbml-cli/src/cli/connector.ts:17:26)
    at Object.<anonymous> (/Users/asadali/Downloads/dbml-master/packages/dbml-cli/src/cli/connector.ts:28:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.m._compile (/Users/asadali/.nvm/versions/node/v20.11.0/lib/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/asadali/.nvm/versions/node/v20.11.0/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
```

This was due to [fetchSchemaJson](https://github.com/holistics/dbml/blob/master/packages/dbml-connector/src/connectors/mssqlConnector.ts#L580) is generating duplicate Refs

```
{
      "name": "FK_WebPortal_Security_User_Type_Lst_WebPortal_Security_User_Types1",
      "endpoints": [
        {
          "tableName": "WebPortal_Security_User_Type_Lst",
          "schemaName": "dbo",
          "fieldNames": [
            "User_Type_ID"
          ],
          "relation": "*"
        },
        {
          "tableName": "WebPortal_Security_User_Types",
          "schemaName": "dbo",
          "fieldNames": [
            "User_Type_ID"
          ],
          "relation": "1"
        }
      ],
      "onDelete": null,
      "onUpdate": null
    },
    {
      "name": "FK_WebPortal_Security_User_Type_Lst_WebPortal_Security_User_Types",
      "endpoints": [
        {
          "tableName": "WebPortal_Security_User_Type_Lst",
          "schemaName": "dbo",
          "fieldNames": [
            "User_Type_ID"
          ],
          "relation": "*"
        },
        {
          "tableName": "WebPortal_Security_User_Types",
          "schemaName": "dbo",
          "fieldNames": [
            "User_Type_ID"
          ],
          "relation": "1"
        }
      ],
      "onDelete": "CASCADE",
      "onUpdate": "CASCADE"
    }
```

Upon removing. it was able to generate the dbml successfully. 

I am pretty sure a group-by command for uniqueness in enums and refs can fix this issue.

**Comment by huyphung1602** [comment]
Hi there, thank you for contacting us. We are currently looking into the issue and will get back to you later.

**Comment by huyleminh01** [comment]
Hi @asadcr ,

> I am pretty sure a group-by command for uniqueness in enums and refs can fix this issue.

This solution is possible, but we have to detect the root cause of the issue.

To do that, can you help provide us with your table structure (if possible)? You can send it via david.bui@holistics.io, and we ensure that your information is protected and used for the debugging purpose only.

Thanks.

**Comment by asadcr** [comment]
@huyleminh01 i think the above data gives a lot of information. if you need any more info i will be happy to provide that. I have debugged already FYI so if u want some intermediate results in code, i can also provide

**Comment by huyleminh01** [comment]
Hi @asadcr ,

Thank you for replying.

Also, it seems I reproduce your case.

Here is my sql:
```sql
CREATE TABLE AddressInfo (
    AddressID UNIQUEIDENTIFIER NOT NULL,
    AddressFormatID UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT CK_Address_Valid CHECK (
        AddressID IN ('176029FA-D6D3-49E1-A48C-000000000001', '176029FA-D6D3-49E1-A48C-000000000002') AND
        AddressFormatID IN ('176029FA-D6D3-49E1-A48C-000000000001', '176029FA-D6D3-49E1-A48C-000000000002')
    )
);
go
``` 

So supprisingly, I got the duplicated enum:
```json
"enums": [
        {
            "name": "CK_Address_Valid",
            "schemaName": "dbo",
            "values": [
                {
                    "name": "176029FA-D6D3-49E1-A48C-000000000002"
                },
                {
                    "name": "176029FA-D6D3-49E1-A48C-000000000001"
                },
                {
                    "name": "176029FA-D6D3-49E1-A48C-000000000002"
                },
                {
                    "name": "176029FA-D6D3-49E1-A48C-000000000001"
                }
            ]
        },
        {
            "name": "CK_Address_Valid",
            "schemaName": "dbo",
            "values": [
                {
                    "name": "176029FA-D6D3-49E1-A48C-000000000002"
                },
                {
                    "name": "176029FA-D6D3-49E1-A48C-000000000001"
                },
                {
                    "name": "176029FA-D6D3-49E1-A48C-000000000002"
                },
                {
                    "name": "176029FA-D6D3-49E1-A48C-000000000001"
                }
            ]
        }
    ],
```

So I will fix it and get back to you later.

**Comment by jessica-bauer** [comment]
Hello, I'm not sure if I'm receiving the same error as mentioned here (I'm new to dbdocs and code in general) so please let me know if not and if you can point me in the right direction, I'd appreciate it. 

I get the following error when trying to generate dbml from a MySQL database:
```
Connecting to database... done.
✖ Generating DBML ...
 ›   Error: Error: Reference with the same endpoints already exists: "fund_transfers"("student_id") references "students"("student_id")
```

**Comment by asadcr** [comment]
was this fixed ?

**Comment by huyleminh01** [comment]
Hi @asadcr ,

We released a fixed version for your issue. Please update your packages to `v3.10.2`.

**Comment by huyleminh01** [comment]
Hi @jessica-bauer,

I'm not sure if your issue is the same as the duplicated one in the MSSQL connector. Maybe let's try to reproduce it first.

**Comment by huyleminh01** [comment]
Hi @jessica-bauer,

I've just reproduced a case that leads to your error.
```sql
CREATE TABLE ref1 (
    id1 INT UNSIGNED,
    id1_part2 INT UNSIGNED,  -- Adding a second column to make a composite key possible
    CONSTRAINT pk_ref1 PRIMARY KEY (id1, id1_part2)  -- Making it a composite primary key
);

CREATE TABLE ref2 (
    id2 INT UNSIGNED PRIMARY KEY,
    ref21 INT UNSIGNED,
    ref22 INT UNSIGNED  -- Adding a second column for the composite foreign key
);

alter table ref2 add constraint foreign key (ref21) references ref1 (id1);
alter table ref1 add constraint foreign key (id1) references ref2 (ref21);
```

And I got `ERROR: Error: Reference with the same endpoints already exists: "ref2"("ref21") references "ref1"("id1")`

Not sure if your DB looks like this one. If yes, then the error is intentional since DBML does not support a circular relationship with the same columns.

**Comment by jessica-bauer** [comment]
@huyleminh01 Thank you so much for replicating the error for me. Yes, that's the same error I am receiving and thank you for confirming that it is intentional within DBML. I appreciate your time.

**Comment by huyleminh01** [comment]
Hi @jessica-bauer,

Thanks for confirming!
